query Articles($category: String!) {
  articles( where: { category: { name: $category },topPick: true },sort: "published_at:desc", limit: 4  ) {
    id
    title
    description
    category {
    	name 
    }
    tags {
      name
    }
    slug
    image {
      url
      formats
    }
    featuredImage {
        url
    }
  }
}