query Articles {
   articles(sort: "published_at:asc", limit: 6) {
    id
    slug
    title
    description
    category {
        name 
    }
    tags {
      name
    }
    image {
      url,
      formats
    }
    published_at
  }
}