query Articles($tag: String!) {
  articles(sort: "published_at:desc", where: { tags: { name: $tag } }  ) {
    id
    title
    description
    category {
    	name 
    }
    tags {
      name
    }
    slug
    image {
      url
      formats
    }
     published_at
  }
}