query Articles($category: String!) {
  articles(sort: "published_at:desc", where: { category: { name: $category } }  ) {
    id
    title
    description
    category {
    	name 
    }
    tags {
      name
    }
    slug
    image {
      url
      formats
    }
     published_at
  }
}