# Write your query or mutation here
query Articles {
   articles(sort: "published_at:asc",where: { featured: true } limit: 4) {
    id
    slug
    title
    category {
        name 
    }
    tags {
      name
    }
    image {
      url,
      formats
    }
    featuredImage {
      url
      formats
    }
     published_at
  }
}