query Article($start: Int!, $limit: Int!, $searchTerm: String!) {
  articles(sort: "published_at:asc", start: $start, limit: $limit, where: 
    { 
    _or: [{ title_contains: $searchTerm}, {description_contains: $searchTerm}] 
    }) {
    id
  }
}
