name: auto deploy 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  repository_dispatch:
    types: 
      - webhook
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.DISPATCH_HOOK_TOKEN }}
          submodules: recursive

      - name: Pull the content
        run: git pull
        
      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DISPATCH_HOOK_TOKEN }}
          publish_dir: ./dist
